/* Turns img/credits.json into credits.js, the photo table the pages read.
     node gen-credits.js           -> src points at the img/ files (multi-page site)
     node gen-credits.js --inline  -> src is a data: URI (one-file build)
   Attribution has to travel with the pictures, so author and licence live in
   the same table as the file name. */

const fs = require('fs');
const path = require('path');

const inline = process.argv.includes('--inline');
const dir = path.join(__dirname, 'img');
const credits = JSON.parse(fs.readFileSync(path.join(dir, 'credits.json'), 'utf8'));

const mime = (f) => (f.endsWith('.png') ? 'image/png' : 'image/jpeg');

const table = {};
for (const [slug, c] of Object.entries(credits)) {
  const file = path.join(dir, c.file);
  if (!fs.existsSync(file)) { continue; }
  table[slug] = {
    src: inline
      ? 'data:' + mime(c.file) + ';base64,' + fs.readFileSync(file).toString('base64')
      : 'img/' + c.file,
    caption: c.caption,
    author: c.author,
    licence: c.licence,
    source: c.source
  };
}

const out = '/* generated by gen-credits.js — do not edit */\nwindow.PHOTOS = ' +
  JSON.stringify(table) + ';\n';
fs.writeFileSync(path.join(__dirname, 'credits.js'), out);
console.log('credits.js: ' + Object.keys(table).length + ' photos, ' +
  Math.round(out.length / 1024) + ' KB' + (inline ? ' (inlined)' : ''));
